Repository cse110-fa22-group24/cse110-fa22-group24, pull requests merged in 2022-12, with the labels that each got.

#81 Add statusvideo1.md
  admin/videos/statusvideo1.md
Labels: admin

#79 Add Profile Button Confetti
  source/index.html
  source/scripts/js-confetti.browser.js
  source/scripts/main.js
Labels: frontend, sprint 3

#83 Fix Lighthouse Issues and Add Report
  admin/Lighthouse Report.pdf
  source/index.html
  source/reference/job-details.html
  source/reference/sort-bar.html
  source/scripts/JobDetails.js
  source/scripts/SortBar.js
  source/styles/job-details.css
  source/styles/sort-bar.css
Labels: frontend, admin, sprint 3

#82 Add Sorting
  source/scripts/SortBar.js
  source/scripts/main.js
Labels: frontend, sprint 3

#77 Backend tests
  package-lock.json
  package.json
  source/test/JobAppDB.test.js
Labels: backend

#86 Added end-to-end tests
  source/test/endToEnd.test.js
Labels: frontend, backend, testing

#88 Update README.md GH Actions
  README.md
Labels: documentation, pipeline
